language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo

script:
  - cargo check --verbose
  # The the debug binary is used for testing
  - cargo build --verbose && cargo test  --verbose
